/* Common */
export const COMMON__SET_DIMENSION = "COMMON__SET_DIMENSION";
export const COMMON__ON_CHANGE_FIELD = "COMMON__ON_CHANGE_FIELD";
export const COMMON__FETCH_REQUEST = "COMMON__FETCH_REQUEST";
export const COMMON__FETCH_REQUEST_COMPLETE = "COMMON__FETCH_REQUEST_COMPLETE";

/* ITEM */
export const ITEM__FETCH_ITEMS = "ITEM__FETCH_ITEMS";
export const ITEM__FETCH_ITEMS_105 = "ITEM__FETCH_ITEMS_105";
export const ITEM__FETCH_ITEM_DETAIL = "ITEM__FETCH_ITEM_DETAIL";
export const ITEM__INIT_ITEMS = "ITEM__INIT_ITEMS";
export const ITEM__ON_CHANGE_FIELD = "ITEM__ON_CHANGE_FIELD";

/* CHARACTER */
export const CHARACTER__INIT = "CHARACTER__INIT";
export const CHARACTER__ON_CHANGE_FIELD = "CHARACTER__ON_CHANGE_FIELD";
export const CHARACTER__FETCH_ITEMS = "CHARACTER__FETCH_ITEMS";
export const CHARACTER__FETCH_INFO = "CHARACTER__FETCH_INFO";
export const CHARACTER__FETCH_EQUIPMENT = "CHARACTER__FETCH_EQUIPMENT";
export const CHARACTER__FETCH_TIMELINE = "CHARACTER__FETCH_TIMELINE";